---
- name: copy example confs to main conf
  command: chdir={{ graphite_target_dir }}/conf
           creates={{ graphite_target_dir }}/conf/{{ item }}
           cp {{ item }}.example {{ item }}
  with_items: "{{ graphite_carbon_conf_files }}"

- name: setup sqlite
  shell: "{{graphite_python}} {{graphite_target_dir}}/bin/django-admin.py migrate --settings=graphite.settings"
  args:
    chdir: "{{graphite_target_dir}}/webapp/graphite"
  environment:
    PYTHONPATH: "{{ graphite_target_dir }}/webapp"
